### PR TITLE
Fix minor bugs 01

### PR DESCRIPTION
**Pull request by aunindadf**
Main Fixes:
1. A loading gif is added while loading the map markers
2. The loading gif containers are optimised for mobile viewing.
3. Menu buttons are optimised so that they can be clicked on from a smaller screen.
4. Fixed the inivisble map issue on country summary page in small screens.

File Changes:
1.  **public/javascripts/countrypagemap.js** - the gif loader for the map  marker is added to the getJSON method.
2. **public/stylesheets/aip-styles.css** - Removed the hidden style option for maps on small screens.
3. **public/stylesheets/main.css** - Optimised the font-size and loading gif container for mobile view.
4.  **views/countries/country.html.erb** - Added the map marker loader gif container.
5. **views/layouts/landing.erb** - Optimised loading gif container for mobile view.
6. **views/layouts/layout.erb** - Optimised loading gif container for mobile view.
7. **views/layouts/layout_forms.erb** - Optimised loading gif container for mobile view.
8. **views/partials/_countries-tabs.html.erb** - Optimised menu buttons for mobile view.
9. **views/partials/_location-tabs.html.erb** - Optimised menu buttons for mobile view.
10. **views/partials/_project_list.html.erb** - Optimised loading gif container for mobile view.
11. **views/partials/_projects-header.html.erb** - Optimised menu buttons for mobile view.
12. **views/partials/_regions-tabs.html.erb** - Optimised menu buttons for mobile view.
13. **views/search/search.html.erb** - Optimised loading gif container for mobile view.

Note: The font-size optimisation works with modern browsers.

### CODE REVIEW

**Comment by johnadamsDFID** [comment]
Rumy, this looks good. 

Would you make a few small changes before we merge this please?

1. Don't display the search field in the menu bar.  In aip-styles.css, keep display:none on #global-header #search

1. Do you need a fallback for older browsers when using vw units? See http://stackoverflow.com/questions/14431411/pure-css-to-make-font-size-responsive-based-on-dynamic-amount-of-characters. Although coverage looks fairly comprehensive. http://caniuse.com/#feat=viewport-units

1. Remove inline styles in your modal html - move into a css class instead.

**Comment by aunindadf** [comment]
Hi John,
Let me answer in sequential order:
1. Updated.
2. Well you have already seen that most of the browsers are already updated with this feature support. Still if there's a need for a fall back then probably we should use some js manipulation or media query. But, is it necessary?
3. Moved the inline codes to main.css file.

**Comment by johnadamsDFID** [comment]
Thanks Rumy. I think 2 is as simple as adding a font-size:14px (whatever the default size needs to be) on a line above the font-size: 0.3vw. I think that sets a value older browsers can handle.

**Comment by aunindadf** [comment]
Yep. I left it commented out last time for one of the loading container but now I added it for the rest also.

**Comment by johnadamsDFID** [comment]
Hi Rumy, I think you've added too many font-size: vw elements. It is making things like the core navigation, headers and other elements much too small on small screens. Can you remove all vw sizing except where you need it (is that just on the map overlay?)

**Pull request merged**
